CREATE DATABASE wordpress;
CREATE USER 'medeana'@'%' IDENTIFIED BY '123123';
GRANT ALL PRIVILEGES ON wordpress.* TO 'medeana'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root123123';